name: Deploy Preview Site

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    if: github.event.label.name == 'request-preview-deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.117.0'
      - name: Build site
        run: hugo
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: 'public/'
          branch: ${{ github.event.pull_request.head.ref }}
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :sparkles: Your changes have been deployed to a preview environment! :sparkles:
            Please visit ${{ steps.deploy.outputs.alias }}) to see how your changes are reflected on the site.
            Please verify everything looks as expected. Thank you for your contribution :rocket:!
          edit-mode: 'replace'
      - name: Remove Label
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const labelToRemove = 'request-preview-deployment';
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              name: labelToRemove
            });
